import { db } from "@workspace/db";
import { goalLibraryTable } from "@workspace/db/schema";
import { eq } from "drizzle-orm";

type NewGoal = {
  idObjetivo: string;
  nombreObjetivo: string;
  modulo: string;
  area: string;
  areaClinica: string;
  subarea: string;
  franjaEtaria: string;
  franjaEtariaMin: number;
  franjaEtariaMax: number;
  nivelDificultad: "básico" | "intermedio" | "avanzado";
  estadoBanco: "activo";
  definicionOperativa: string;
};

const GOALS: NewGoal[] = [
  // ─────────────────────────────────────────────────────────────────────
  // LENGUAJE (NL) — 28 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "NL-2-4-LEX-B-01",
    nombreObjetivo: "Nombrar objetos cotidianos del entorno inmediato",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Léxico", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente nombrará al menos 10 objetos cotidianos (taza, silla, zapato, etc.) cuando el terapeuta los señale o presente, con un 80 % de precisión en 3 sesiones consecutivas.",
  },
  {
    idObjetivo: "NL-2-4-LEX-B-02",
    nombreObjetivo: "Señalar imágenes de objetos al escuchar su nombre",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Léxico", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente señalará correctamente la imagen del objeto nombrado en un campo de 4 imágenes, con un 80 % de aciertos.",
  },
  {
    idObjetivo: "NL-2-4-COM-B-01",
    nombreObjetivo: "Comprender frases simples de acción (dame, pon, trae)",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Comprensión", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente ejecutará consignas verbales de un paso (dame el vaso, pon la pelota) sin apoyo gestual en un 80 % de los intentos.",
  },
  {
    idObjetivo: "NL-2-4-MOR-B-01",
    nombreObjetivo: "Combinar dos palabras para expresar posesión o acción",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Morfosintaxis", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá combinaciones de dos palabras (mamá agua, nene come) de forma espontánea en contextos de juego, al menos 5 combinaciones diferentes por sesión.",
  },
  {
    idObjetivo: "NL-2-4-SEM-B-01",
    nombreObjetivo: "Relacionar palabras con su imagen y función en contexto",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Semántica", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente asociará 10 palabras con su imagen y función cuando el terapeuta pregunte '¿para qué sirve?', completando al menos 8 de 10 en forma correcta.",
  },
  {
    idObjetivo: "NL-4-6-LEX-B-01",
    nombreObjetivo: "Nombrar acciones representadas en imágenes",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Léxico verbal", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente nombrará verbos de acción (correr, comer, saltar, dormir) al ver imágenes, con un 80 % de precisión en 3 sesiones.",
  },
  {
    idObjetivo: "NL-4-6-LEX-B-02",
    nombreObjetivo: "Identificar categorías semánticas básicas (frutas, animales, ropa)",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Categorías semánticas", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente clasificará tarjetas en al menos 5 categorías semánticas distintas, ubicando correctamente el 80 % de los ítems.",
  },
  {
    idObjetivo: "NL-4-6-COM-B-01",
    nombreObjetivo: "Seguir instrucciones de dos pasos sin apoyo gestual",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Comprensión", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente seguirá instrucciones verbales de dos pasos (agarra el lápiz y ponlo en la caja) sin apoyo gestual con un 80 % de aciertos.",
  },
  {
    idObjetivo: "NL-4-6-MOR-B-01",
    nombreObjetivo: "Producir oraciones con sujeto, verbo y complemento",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Morfosintaxis", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá oraciones de al menos 3 elementos (S+V+O) de forma espontánea al describir escenas de imágenes, en el 75 % de las oportunidades.",
  },
  {
    idObjetivo: "NL-4-6-SEM-B-01",
    nombreObjetivo: "Relacionar palabras por asociación funcional (cuchara-plato)",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Semántica relacional", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente emparejará al menos 10 pares de palabras relacionadas funcionalmente (cepillo-peine, zapato-calcetín) con un 80 % de aciertos.",
  },
  {
    idObjetivo: "NL-4-6-LEX-M-01",
    nombreObjetivo: "Usar vocabulario descriptivo (color, tamaño, forma)",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Léxico descriptivo", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente describirá objetos usando al menos 3 atributos (color, tamaño, forma) de forma espontánea al describir imágenes o juguetes, con un 80 % de precisión.",
  },
  {
    idObjetivo: "NL-4-6-MOR-M-01",
    nombreObjetivo: "Usar correctamente artículos definidos e indefinidos y preposiciones básicas",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Morfología gramatical", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente usará artículos (el, la, un, una) y preposiciones (en, sobre, debajo) correctamente en oraciones espontáneas con un 80 % de precisión.",
  },
  {
    idObjetivo: "NL-4-6-COM-M-01",
    nombreObjetivo: "Comprender absurdos verbales simples",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Comprensión inferencial", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará y explicará qué es incorrecto en oraciones absurdas simples (El pescado sube a los árboles) en el 80 % de los ítems presentados.",
  },
  {
    idObjetivo: "NL-4-6-NAR-M-01",
    nombreObjetivo: "Narrar un cuento corto con inicio, desarrollo y final",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Narrativo", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente narrará un cuento de 3 imágenes secuenciadas incluyendo personaje, acción y resolución, usando conectores temporales básicos (primero, después, al final).",
  },
  {
    idObjetivo: "NL-4-6-INF-M-01",
    nombreObjetivo: "Anticipar finales de cuentos usando claves del contexto",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Inferencias", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente anticipará el desenlace de un cuento antes de escuchar el final, usando información contextual, con justificación coherente en el 75 % de los intentos.",
  },
  {
    idObjetivo: "NL-6-8-LEX-M-01",
    nombreObjetivo: "Comprender y usar antónimos y sinónimos en contexto",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Relaciones léxicas", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará y producirá sinónimos y antónimos de palabras frecuentes de uso escolar con un 80 % de aciertos en actividades estructuradas.",
  },
  {
    idObjetivo: "NL-6-8-MOR-M-01",
    nombreObjetivo: "Usar formas verbales en pasado y futuro correctamente",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Morfología verbal", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá verbos regulares e irregulares frecuentes en tiempo pasado y futuro con concordancia de persona y número, con un 80 % de precisión.",
  },
  {
    idObjetivo: "NL-6-8-COM-M-01",
    nombreObjetivo: "Realizar inferencias causales en textos escuchados",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Comprensión inferencial", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "Tras escuchar un texto breve, el paciente responderá preguntas de causa-efecto (¿por qué ocurrió esto?) con respuestas ajustadas al texto en el 80 % de los casos.",
  },
  {
    idObjetivo: "NL-6-8-NAR-M-01",
    nombreObjetivo: "Narrar experiencias personales con secuencia lógica",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Narrativo personal", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente narrará un evento personal con mínimo 5 oraciones, incluyendo contexto, acciones y desenlace, usando marcadores temporales con coherencia.",
  },
  {
    idObjetivo: "NL-6-8-DIS-M-01",
    nombreObjetivo: "Usar conectores temporales y causales en el discurso oral",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Discurso oral", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente usará conectores (porque, entonces, después, sin embargo) de forma apropiada al narrar o explicar situaciones, con un mínimo de 4 conectores distintos por muestra de habla.",
  },
  {
    idObjetivo: "NL-6-8-LEX-A-01",
    nombreObjetivo: "Comprender y usar vocabulario académico en contexto escolar",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Léxico académico", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente comprenderá y usará vocabulario de dominio escolar (clasificar, comparar, describir, explicar) en tareas académicas con un 80 % de precisión.",
  },
  {
    idObjetivo: "NL-6-8-MOR-A-01",
    nombreObjetivo: "Producir oraciones subordinadas con concordancia correcta",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Sintaxis compleja", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá oraciones con cláusulas subordinadas causales, temporales o relativas con concordancia correcta en el 80 % de las producciones espontáneas.",
  },
  {
    idObjetivo: "NL-6-8-NAR-A-01",
    nombreObjetivo: "Producir narraciones con perspectiva de múltiples personajes",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Narrativo avanzado", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente narará historias incluyendo el punto de vista de al menos 2 personajes distintos, con atribución de estados mentales y emociones diferenciados.",
  },
  {
    idObjetivo: "NL-6-8-SEM-A-01",
    nombreObjetivo: "Comprender lenguaje figurado: metáforas y analogías",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Semántica avanzada", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente explicará el significado de expresiones figuradas (tiene manos de seda, es rápido como un rayo) con paráfrasis ajustada en el 80 % de los ítems.",
  },
  {
    idObjetivo: "NL-6-8-INF-A-01",
    nombreObjetivo: "Realizar inferencias pragmáticas en situaciones cotidianas",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Inferencias pragmáticas", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente inferirá la intención del hablante en situaciones no literales (ironía, indirectas) y explicará correctamente el significado implícito en el 75 % de los casos.",
  },
  {
    idObjetivo: "NL-6-8-DIS-A-01",
    nombreObjetivo: "Producir discurso expositivo estructurado con argumentos",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Discurso expositivo", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente expondrá un tema de su interés durante 2 minutos con introducción, al menos 2 argumentos y cierre, usando vocabulario preciso y conectores lógicos.",
  },
  {
    idObjetivo: "NL-4-6-REL-M-01",
    nombreObjetivo: "Identificar relaciones parte-todo en objetos y seres vivos",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Relaciones semánticas", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará la parte de un todo al escuchar el nombre del todo (rueda → auto) y viceversa, con un 80 % de aciertos en 20 ítems.",
  },
  {
    idObjetivo: "NL-4-6-EXP-B-01",
    nombreObjetivo: "Expresar preferencias y rechazos usando oraciones simples",
    modulo: "Lenguaje", area: "Lenguaje", areaClinica: "lenguaje",
    subarea: "Expresión oral", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente expresará sus preferencias y rechazos con oraciones de al menos dos elementos (quiero jugar, no me gusta eso) de forma espontánea en el contexto de la sesión.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // HABLA (HB) — 20 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "HB-2-4-ART-B-01",
    nombreObjetivo: "Producir vocales y consonantes bilabiales en posición inicial",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Articulación", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá las vocales y las consonantes /p/, /b/, /m/ en posición inicial de sílaba al imitar al terapeuta con un 80 % de precisión articulatoria.",
  },
  {
    idObjetivo: "HB-2-4-FON-B-01",
    nombreObjetivo: "Reducir el proceso fonológico de omisión de consonante final",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Procesos fonológicos", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá palabras CV+C (pan, sol, mar) conservando la consonante final en el 80 % de los intentos en actividades dirigidas.",
  },
  {
    idObjetivo: "HB-2-4-DIS-B-01",
    nombreObjetivo: "Discriminar auditivamente palabras monosílabas de dos sílabas",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Discriminación auditiva", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente señalará la imagen correcta entre dos alternativas (palabras que difieren en longitud silábica) al escuchar la palabra, con un 80 % de aciertos.",
  },
  {
    idObjetivo: "HB-4-6-ART-B-01",
    nombreObjetivo: "Producir fonemas fricativos /f/ y /s/ en posición inicial y media",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Articulación", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá /f/ y /s/ en palabras y frases cortas en posición inicial y media con un 80 % de corrección articulatoria en sesión.",
  },
  {
    idObjetivo: "HB-4-6-FON-B-01",
    nombreObjetivo: "Reducir el proceso de sustitución de fonemas velares por alveolares",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Procesos fonológicos", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá palabras con /k/ y /g/ sin sustituirlas por /t/ y /d/ en el 80 % de los intentos en actividades estructuradas.",
  },
  {
    idObjetivo: "HB-4-6-DIS-B-01",
    nombreObjetivo: "Discriminar pares mínimos que difieren en un único fonema",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Discriminación auditiva", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente señalará correctamente la imagen correspondiente al par mínimo escuchado (pala/bala, cama/gama) con un 85 % de aciertos.",
  },
  {
    idObjetivo: "HB-4-6-ART-M-01",
    nombreObjetivo: "Producir el fonema /r/ simple en posición intervocálica",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Articulación", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá el fonema /r/ simple (cara, puro, torero) en palabras y frases con un 80 % de precisión tras práctica en nivel de sílaba y palabra.",
  },
  {
    idObjetivo: "HB-4-6-FON-M-01",
    nombreObjetivo: "Producir grupos consonánticos en posición inicial de sílaba (tr, cl, br)",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Sílabas complejas", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá palabras con grupos consonánticos de dos elementos (tren, clavo, brazo) sin simplificar la estructura silábica en el 75 % de los intentos.",
  },
  {
    idObjetivo: "HB-4-6-FLU-B-01",
    nombreObjetivo: "Aplicar técnica de habla lenta y fluida en lectura oral de palabras",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Fluidez", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente leerá listas de palabras aplicando habla lenta y continua (prolongación vocálica inicial) con menos de 3 disfluencias por cada 100 palabras.",
  },
  {
    idObjetivo: "HB-4-6-PRO-M-01",
    nombreObjetivo: "Usar patrones de entonación adecuados en oraciones declarativas e interrogativas",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Prosodia", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá oraciones declarativas e interrogativas con contorno entonativo diferenciado y reconocible por el oyente en el 80 % de las producciones.",
  },
  {
    idObjetivo: "HB-6-8-ART-M-01",
    nombreObjetivo: "Producir el fonema /rr/ múltiple en distintas posiciones de palabra",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Articulación", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá el vibrante múltiple /rr/ en palabras y frases con un 80 % de precisión articulatoria en habla espontánea y dirigida.",
  },
  {
    idObjetivo: "HB-6-8-FON-M-01",
    nombreObjetivo: "Aplicar reglas de acentuación en palabras de más de tres sílabas",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Prosodia léxica", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente acentuará correctamente palabras esdrújulas y sobresdrújulas al leer en voz alta, con un 80 % de precisión en una muestra de 30 palabras.",
  },
  {
    idObjetivo: "HB-6-8-FLU-M-01",
    nombreObjetivo: "Reducir disfluencias en situaciones de presión comunicativa",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Fluidez", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente mantendrá menos de 5 disfluencias por cada 100 sílabas en conversación con el terapeuta aplicando técnicas de modificación del tartamudeo.",
  },
  {
    idObjetivo: "HB-6-8-FLU-A-01",
    nombreObjetivo: "Generalizar técnicas de fluidez a situaciones comunicativas naturales",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Fluidez generalizada", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente aplicará técnicas de fluidez (control de velocidad, inicio suave) en conversaciones con personas externas a la sesión, con un máximo de 5 % de disfluencias reportadas.",
  },
  {
    idObjetivo: "HB-6-8-DIS-M-01",
    nombreObjetivo: "Discriminar y producir fonemas de difícil adquisición en habla espontánea",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Discriminación y producción", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará y producirá correctamente los fonemas trabajados en el contexto de habla espontánea con autocorrección espontánea en el 70 % de los errores.",
  },
  {
    idObjetivo: "HB-6-8-ART-A-01",
    nombreObjetivo: "Generalizar la correcta articulación de fonemas trabajados al habla espontánea",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Generalización articulatoria", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá los fonemas trabajados correctamente en conversación espontánea en ambientes fuera de la sesión clínica, según reporte del familiar y observación directa.",
  },
  {
    idObjetivo: "HB-2-4-ART-B-02",
    nombreObjetivo: "Imitar secuencias de consonante-vocal en juegos de imitación",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Imitación fonética", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente imitará secuencias CV presentadas por el terapeuta (ma, pa, ba, ta, da) con precisión articulatoria en el 80 % de los intentos en contexto lúdico.",
  },
  {
    idObjetivo: "HB-4-6-VEL-M-01",
    nombreObjetivo: "Regular la velocidad del habla en discurso oral espontáneo",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Velocidad y ritmo", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente regulará su velocidad de habla a un ritmo moderado (entre 120-150 palabras por minuto) al narrar situaciones o describir imágenes en sesión.",
  },
  {
    idObjetivo: "HB-4-6-DIS-M-01",
    nombreObjetivo: "Discriminar fonemas fricativos y oclusivos sordos y sonoros",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Discriminación fonémica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente discriminará auditivamente pares mínimos con contraste sordo/sonoro (/f/-/v/, /p/-/b/, /t/-/d/) con un 85 % de aciertos en 30 ítems presentados.",
  },
  {
    idObjetivo: "HB-6-8-PRO-M-01",
    nombreObjetivo: "Usar variaciones prosódicas para transmitir estados emocionales",
    modulo: "Habla", area: "Habla", areaClinica: "habla",
    subarea: "Prosodia expresiva", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente modulará el tono, intensidad y velocidad de su habla para expresar diferentes estados emocionales (alegría, sorpresa, tristeza) de forma reconocible en el 80 % de los intentos.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // PRAGMÁTICA (PR) — 20 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "PR-2-4-AT-B-01",
    nombreObjetivo: "Establecer y mantener atención conjunta con el adulto",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Atención conjunta", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente seguirá la mirada y el gesto de señalar del adulto para enfocar su atención en un objeto o evento, y lo mirará al adulto en el 75 % de las oportunidades.",
  },
  {
    idObjetivo: "PR-2-4-FUN-B-01",
    nombreObjetivo: "Usar funciones comunicativas básicas: pedir, rechazar y saludar",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Funciones comunicativas", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente usará medios verbales y/o gestuales intencionales para pedir objetos, rechazar actividades y saludar en al menos 3 contextos distintos.",
  },
  {
    idObjetivo: "PR-2-4-PET-B-01",
    nombreObjetivo: "Realizar peticiones verbales espontáneas para obtener objetos o actividades",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Petición", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente solicitará verbalmente objetos o actividades deseados (dame, quiero, más) de forma espontánea sin que el adulto los ofrezca previamente, en el 75 % de las oportunidades.",
  },
  {
    idObjetivo: "PR-2-4-TUR-B-01",
    nombreObjetivo: "Respetar los turnos en interacciones de juego compartido",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Turnos comunicativos", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente esperará su turno en juegos de intercambio de objetos y actividades de 2 participantes, respetándolo en al menos el 70 % de las oportunidades.",
  },
  {
    idObjetivo: "PR-4-6-FUN-B-01",
    nombreObjetivo: "Usar formas de cortesía básica en intercambios comunicativos",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Cortesía lingüística", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente utilizará formas de cortesía (por favor, gracias, perdón) de forma espontánea y apropiada al contexto en al menos el 75 % de las situaciones que lo requieren.",
  },
  {
    idObjetivo: "PR-4-6-TUR-M-01",
    nombreObjetivo: "Mantener un tema conversacional por al menos 4 turnos consecutivos",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Mantenimiento del tópico", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente participará en conversaciones sobre un tema elegido por al menos 4 intercambios consecutivos sin desviarse del tópico, en el 75 % de los intentos.",
  },
  {
    idObjetivo: "PR-4-6-FUN-M-01",
    nombreObjetivo: "Formular preguntas para obtener información en el contexto conversacional",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Función interrogativa", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente formulará preguntas (qué, quién, dónde, cuándo) de forma espontánea para obtener información faltante en el 70 % de las situaciones de juego o conversación.",
  },
  {
    idObjetivo: "PR-4-6-CON-M-01",
    nombreObjetivo: "Iniciar una conversación con un par de forma apropiada",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Habilidades conversacionales", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente iniciará una conversación con un par o adulto desconocido usando saludos y frases de apertura apropiadas al contexto, en el 70 % de las situaciones de juego grupal.",
  },
  {
    idObjetivo: "PR-4-6-NAR-M-01",
    nombreObjetivo: "Narrar un evento social o escolar de forma coherente a un oyente",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Narrativa social", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente relatará un evento ocurrido en el colegio o en casa con al menos 3 elementos (quién, qué hizo, qué pasó), con información suficiente para que el oyente comprenda.",
  },
  {
    idObjetivo: "PR-4-6-ADP-M-01",
    nombreObjetivo: "Adaptar el tono y el vocabulario según el interlocutor (niño vs adulto)",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Adaptación comunicativa", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente modificará su forma de hablar (vocabulario, tono, longitud de oración) al dirigirse a un niño pequeño vs un adulto, observable en situaciones de juego de roles.",
  },
  {
    idObjetivo: "PR-6-8-CON-M-01",
    nombreObjetivo: "Reparar rupturas comunicativas de forma activa",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Reparación conversacional", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "Cuando el oyente no comprenda, el paciente usará estrategias de reparación (repetir, reformular, agregar información) en el 80 % de las señales de incomprensión del oyente.",
  },
  {
    idObjetivo: "PR-6-8-CON-M-02",
    nombreObjetivo: "Mantener y cambiar tópicos conversacionales de forma apropiada",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Gestión del tópico", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente mantendrá un tema conversacional por al menos 6 turnos y realizará cambios de tema de forma fluida usando marcadores (a propósito, hablando de eso) en el 70 % de los intentos.",
  },
  {
    idObjetivo: "PR-6-8-ADP-M-01",
    nombreObjetivo: "Adaptar el discurso según el contexto formal o informal",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Registro lingüístico", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente modificará su registro lingüístico (vocabulario, construcciones, tono) al pasar de un contexto informal (juego) a uno formal (presentación en clase) de forma observable.",
  },
  {
    idObjetivo: "PR-6-8-NAR-A-01",
    nombreObjetivo: "Narrar historias personales reconociendo las necesidades informativas del oyente",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Perspectiva del oyente", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente proveerá suficiente información de fondo al narrar una experiencia a alguien que no estuvo presente, ajustando la cantidad de detalle según lo que el oyente ya sabe.",
  },
  {
    idObjetivo: "PR-6-8-LNL-A-01",
    nombreObjetivo: "Comprender y usar el sarcasmo y la ironía en contextos apropiados",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Lenguaje no literal", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará la intención irónica o sarcástica de enunciados presentados en viñetas, explicando qué significa realmente el hablante, con un 75 % de aciertos.",
  },
  {
    idObjetivo: "PR-6-8-FUN-A-01",
    nombreObjetivo: "Usar peticiones indirectas apropiadas al contexto social",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Actos de habla indirectos", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente formulará solicitudes de forma indirecta (¿podrías bajar el volumen?) en lugar de imperativos directos, de forma apropiada al contexto social en el 75 % de las oportunidades.",
  },
  {
    idObjetivo: "PR-4-6-PET-B-01",
    nombreObjetivo: "Pedir objetos y acciones usando frases completas",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Petición", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente formulará peticiones usando frases completas (quiero el juego rojo, por favor dame el lápiz) de forma espontánea en el contexto de la sesión en el 80 % de las oportunidades.",
  },
  {
    idObjetivo: "PR-2-4-FUN-B-02",
    nombreObjetivo: "Usar el gesto de señalar con función declarativa e imperativa",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Comunicación gestual", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente señalará objetos distantes para mostrarlos o pedirlos al adulto de forma intencional y consistente, diferenciando entre señalar para compartir (mira) y para pedir (dame).",
  },
  {
    idObjetivo: "PR-6-8-CON-A-01",
    nombreObjetivo: "Participar activamente en una discusión grupal aportando ideas propias",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Discusión grupal", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente participará en una discusión grupal de 3-4 personas aportando al menos 3 contribuciones relevantes, sin interrumpir y respondiendo a las ideas de otros.",
  },
  {
    idObjetivo: "PR-4-6-CON-M-02",
    nombreObjetivo: "Reconocer y reparar malentendidos durante la conversación",
    modulo: "Pragmática", area: "Pragmática", areaClinica: "pragmática",
    subarea: "Reparación conversacional", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "Cuando el oyente muestre señales de no entender (cara de confusión, pregunta), el paciente reformulará su enunciado usando estrategias de clarificación en el 70 % de los casos.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // MOTRICIDAD OROFACIAL (MO) — 18 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "MO-2-4-TON-B-01",
    nombreObjetivo: "Mejorar el tono labial mediante ejercicios activos con resistencia",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Tono muscular labial", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente mantendrá el cierre labial durante al menos 10 segundos mientras el terapeuta aplica resistencia suave en los labios, logrando la meta en 3 de 5 intentos.",
  },
  {
    idObjetivo: "MO-2-4-PRX-B-01",
    nombreObjetivo: "Imitar movimientos labiales básicos (beso, sonrisa, morritos) ante el espejo",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Praxis labiales", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente imitará 5 movimientos labiales distintos (beso, sonrisa, vibración, protrusión, retracción) ante el espejo con el 80 % de precisión en 3 sesiones.",
  },
  {
    idObjetivo: "MO-2-4-RES-B-01",
    nombreObjetivo: "Establecer el patrón de respiración nasal en reposo",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Respiración nasal", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente mantendrá la boca cerrada y la respiración nasal durante actividades sedentarias de 5 minutos, según registro del terapeuta y del familiar.",
  },
  {
    idObjetivo: "MO-2-4-SUC-B-01",
    nombreObjetivo: "Eliminar hábito de succión digital o de chupete con apoyo conductual",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Hábitos orales nocivos", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente reducirá el hábito de succión a menos de 1 episodio por día según reporte del familiar durante 2 semanas consecutivas, con apoyo de estrategias de sustitución.",
  },
  {
    idObjetivo: "MO-2-4-MAS-B-01",
    nombreObjetivo: "Desarrollar masticación bilateral alternada con alimentos de textura blanda",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Masticación", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente masticará alimentos de textura blanda usando ambos lados de la boca alternadamente, sin derramar alimento, en el 70 % de las oportunidades observadas.",
  },
  {
    idObjetivo: "MO-4-6-TON-B-01",
    nombreObjetivo: "Fortalecer musculatura lingual mediante ejercicios de resistencia",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Tono muscular lingual", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente empujará con la lengua contra una espátula durante 5 segundos en 5 repeticiones, manteniendo la posición en al menos 4 de 5 intentos.",
  },
  {
    idObjetivo: "MO-4-6-PRX-B-01",
    nombreObjetivo: "Realizar praxis linguales básicas bajo consigna verbal: sacar, subir, bajar lengua",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Praxis linguales", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente ejecutará 6 praxis linguales distintas bajo consigna verbal sin imitación del terapeuta, con precisión del movimiento en el 80 % de las consignas.",
  },
  {
    idObjetivo: "MO-4-6-DEG-M-01",
    nombreObjetivo: "Corregir el patrón de interposición lingual durante la deglución",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Deglución atípica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente deglutirá saliva con la lengua en posición retroalveolar (sin interposición lingual anterior) en el 80 % de los intentos observados en sesión.",
  },
  {
    idObjetivo: "MO-4-6-RES-M-01",
    nombreObjetivo: "Coordinar la función respiratoria naso-oral con el habla",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Coordinación fono-respiratoria", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente tomará aire antes de iniciar el enunciado y lo administrará de forma continua durante frases de 5-7 palabras, sin pausas inadecuadas por necesidad de aire, en el 75 % de las frases.",
  },
  {
    idObjetivo: "MO-4-6-MAS-M-01",
    nombreObjetivo: "Desarrollar masticación bilateral con alimentos de textura firme",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Masticación", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente masticará alimentos de textura firme (zanahoria, manzana) usando ambos lados de forma coordinada con sellado labial, sin derramar alimento, en el 80 % de las observaciones.",
  },
  {
    idObjetivo: "MO-4-6-TON-M-01",
    nombreObjetivo: "Mejorar el tono de mejillas y bucinadores",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Tono muscular facial", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará ejercicios de inflado y succión de mejillas alternados por al menos 10 repeticiones manteniendo el tono contra resistencia en el 75 % de los intentos.",
  },
  {
    idObjetivo: "MO-6-8-DEG-M-01",
    nombreObjetivo: "Generalizar el patrón de deglución madura a la alimentación cotidiana",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Generalización deglutoria", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El familiar reportará uso del patrón de deglución madura en el 80 % de las comidas, con ausencia de interposición lingual anterior, verificado en sesión con alimentos sólidos.",
  },
  {
    idObjetivo: "MO-6-8-RES-M-01",
    nombreObjetivo: "Sostener proyección de aire oral para soplar vela a 20 cm por 3 segundos",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Soporte respiratorio oral", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente dirigirá y sostendrá un chorro de aire oral continuo capaz de mantener una vela inclinada a 20 cm de distancia durante 3 segundos en 3 de 5 intentos.",
  },
  {
    idObjetivo: "MO-6-8-DEG-A-01",
    nombreObjetivo: "Corregir postura corporal y posición de cabeza durante la deglución",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Postura deglutoria", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente adoptará postura erguida con la cabeza en posición neutra durante la deglución, sin extensión cervical compensatoria, en el 80 % de las ingestas observadas.",
  },
  {
    idObjetivo: "MO-6-8-TON-A-01",
    nombreObjetivo: "Fortalecer musculatura velar para mejorar el cierre velofaríngeo",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Musculatura velar", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente producirá consonantes orales (/p/, /t/, /k/) con adecuado cierre velofaríngeo (sin hipernasalidad audible) en el 80 % de las palabras en habla continua.",
  },
  {
    idObjetivo: "MO-2-4-PRX-B-02",
    nombreObjetivo: "Realizar movimientos linguales de lateralización y elevación",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Praxis linguales", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará movimientos de lateralización y elevación lingual siguiendo el modelo del terapeuta en el espejo, con precisión en 4 de 6 movimientos diferentes.",
  },
  {
    idObjetivo: "MO-4-6-PRX-M-01",
    nombreObjetivo: "Realizar secuencias de praxis orofaciales en orden establecido",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Secuencias praxicas", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente ejecutará secuencias de 3 praxis orofaciales (labiales + linguales + mandibulares) en el orden indicado verbalmente, sin modelo visual, con 80 % de aciertos.",
  },
  {
    idObjetivo: "MO-6-8-PRX-M-01",
    nombreObjetivo: "Realizar praxis diadococinéticas con velocidad y precisión crecientes",
    modulo: "Motricidad Orofacial", area: "Motricidad Orofacial", areaClinica: "motricidad orofacial",
    subarea: "Diadococinesia", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará secuencias AMR (pa-pa-pa, ta-ta-ta) y SMR (pa-ta-ka) con ritmo regular y velocidad apropiada para su edad, con menos de 2 errores en 10 repeticiones.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // COGNICIÓN (CG) — 18 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "CG-2-4-AT-B-01",
    nombreObjetivo: "Mantener atención en una tarea estructurada por 5 minutos",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Atención sostenida", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente completará actividades estructuradas (rompecabezas, encaje de formas) durante 5 minutos continuos sin distraerse ni abandonar la tarea en 3 sesiones consecutivas.",
  },
  {
    idObjetivo: "CG-2-4-CAT-B-01",
    nombreObjetivo: "Clasificar objetos concretos en dos categorías según su función",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Categorización", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente separará objetos de dos categorías distintas (comida vs ropa, animales vs vehículos) colocándolos en recipientes correspondientes con un 80 % de aciertos.",
  },
  {
    idObjetivo: "CG-4-6-AT-B-01",
    nombreObjetivo: "Mantener atención selectiva ante estímulos distractores",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Atención selectiva", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará una tarea de selección de estímulos objetivo (marcar la letra A) ignorando distractores auditivos y visuales durante 5 minutos, con menos del 20 % de errores.",
  },
  {
    idObjetivo: "CG-4-6-CAT-B-01",
    nombreObjetivo: "Clasificar imágenes en categorías semánticas de hasta 5 grupos",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Categorización semántica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente clasificará 25 tarjetas de imágenes en 5 categorías distintas (animales, frutas, ropa, muebles, medios de transporte) con un 80 % de aciertos.",
  },
  {
    idObjetivo: "CG-4-6-MEM-B-01",
    nombreObjetivo: "Recordar una secuencia de 3 objetos presentados visualmente",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Memoria visual", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "Tras observar 3 objetos durante 10 segundos, el paciente los recordará en orden y en desorden con un 80 % de aciertos en 5 ensayos.",
  },
  {
    idObjetivo: "CG-4-6-MEM-M-01",
    nombreObjetivo: "Retener y repetir secuencias de dígitos de longitud creciente",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Memoria auditiva de trabajo", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente repetirá secuencias de dígitos de 3-5 elementos en orden directo e inverso, alcanzando al menos 4 dígitos directos y 3 inversos con 80 % de aciertos.",
  },
  {
    idObjetivo: "CG-4-6-AT-M-01",
    nombreObjetivo: "Sostener la atención dividida en dos tareas simultáneas sencillas",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Atención dividida", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará dos tareas simultáneas de baja demanda (escuchar instrucciones y colorear) manteniendo un desempeño adecuado en ambas en al menos el 70 % de los intentos.",
  },
  {
    idObjetivo: "CG-4-6-EJE-M-01",
    nombreObjetivo: "Planificar los pasos de una tarea secuencial antes de ejecutarla",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Planificación", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente verbalizará los pasos necesarios para completar una tarea antes de iniciarla (armar un rompecabezas, seguir una receta sencilla) en el 75 % de las actividades propuestas.",
  },
  {
    idObjetivo: "CG-4-6-RAZ-M-01",
    nombreObjetivo: "Identificar semejanzas y diferencias entre dos objetos o conceptos",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Razonamiento comparativo", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará al menos 2 semejanzas y 2 diferencias entre pares de objetos o animales cuando el terapeuta se los presente, con un 80 % de aciertos.",
  },
  {
    idObjetivo: "CG-6-8-AT-M-01",
    nombreObjetivo: "Mantener atención sostenida durante actividades académicas por 15 minutos",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Atención sostenida", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente completará actividades académicas estructuradas (copia, lectura guiada) durante 15 minutos continuos con menos de 3 interrupciones por distracción, en 3 sesiones.",
  },
  {
    idObjetivo: "CG-6-8-MEM-M-01",
    nombreObjetivo: "Usar estrategias de memorización (repetición, agrupamiento) para recordar listas",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Estrategias mnemónicas", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente aplicará al menos una estrategia de memorización (repetición en voz alta, agrupamiento por categoría) para recordar listas de 7-9 ítems con un 80 % de retención al cabo de 5 minutos.",
  },
  {
    idObjetivo: "CG-6-8-EJE-M-01",
    nombreObjetivo: "Monitorizar y corregir errores propios durante la ejecución de una tarea",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Monitoreo ejecutivo", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente detectará y corregirá al menos el 70 % de sus propios errores en tareas académicas sin señalización del terapeuta, usando estrategias de autocorrección.",
  },
  {
    idObjetivo: "CG-6-8-EJE-A-01",
    nombreObjetivo: "Establecer metas y organizar pasos para completar un proyecto",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Funciones ejecutivas", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente planificará un proyecto simple (preparar una presentación, organizar un cuento) definiendo 3-4 pasos con secuencia lógica y ejecutándolos con supervisión mínima.",
  },
  {
    idObjetivo: "CG-6-8-RAZ-M-01",
    nombreObjetivo: "Resolver problemas lógicos de clasificación y serie de patrones",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Razonamiento lógico", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente completará series de patrones y clasificaciones lógicas (matrices, analogías visuales) con un 80 % de aciertos en actividades de nivel escolar.",
  },
  {
    idObjetivo: "CG-6-8-RAZ-A-01",
    nombreObjetivo: "Inferir causa y efecto en situaciones cotidianas y académicas",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Razonamiento causal", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente explicará la relación de causa-efecto en situaciones cotidianas y textos leídos, identificando correctamente la causa y consecuencia en el 80 % de los ítems.",
  },
  {
    idObjetivo: "CG-6-8-MEM-A-01",
    nombreObjetivo: "Recuperar información de la memoria a largo plazo para resolver tareas escolares",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Memoria a largo plazo", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente recuperará información aprendida en sesiones previas (vocabulario, reglas, procedimientos) para aplicarla en tareas nuevas con un 80 % de aciertos sin pistas.",
  },
  {
    idObjetivo: "CG-4-6-EJE-M-02",
    nombreObjetivo: "Inhibir respuesta prepotente ante señal de parada (go/no-go)",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Control inhibitorio", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "En tareas tipo go/no-go, el paciente inhibirá su respuesta ante la señal de parada en al menos el 75 % de los ensayos de señal de parada dentro de un bloque de 20 intentos.",
  },
  {
    idObjetivo: "CG-6-8-EJE-M-02",
    nombreObjetivo: "Mantener la flexibilidad cognitiva al cambiar de regla en una tarea",
    modulo: "Cognición", area: "Cognición", areaClinica: "cognición",
    subarea: "Flexibilidad cognitiva", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente cambiará de regla de clasificación (de color a forma a cantidad) en una tarea de cartas al menos 3 veces sin perseveración de errores mayor al 20 %.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // LECTOESCRITURA (LE) — 15 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "LE-4-6-CON-B-01",
    nombreObjetivo: "Segmentar palabras en sílabas con palmadas",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Conciencia silábica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente segmentará palabras de 2-4 sílabas en sílabas usando palmadas, con un 80 % de precisión en una lista de 20 palabras presentadas oralmente.",
  },
  {
    idObjetivo: "LE-4-6-CON-B-02",
    nombreObjetivo: "Identificar la sílaba inicial y final de palabras",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Conciencia silábica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará la sílaba inicial y final de palabras dichas por el terapeuta con un 80 % de aciertos en 20 palabras de distinta estructura silábica.",
  },
  {
    idObjetivo: "LE-4-6-CON-M-01",
    nombreObjetivo: "Identificar y manipular fonemas iniciales en palabras (segmentación fonémica)",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Conciencia fonémica", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente identificará el fonema inicial de palabras cortas y buscará otras palabras que empiecen igual, con un 80 % de aciertos en 20 ítems.",
  },
  {
    idObjetivo: "LE-4-6-LEC-B-01",
    nombreObjetivo: "Reconocer las letras del alfabeto por su nombre y sonido",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Conocimiento alfabético", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente nombrará correctamente al menos 20 de las 27 letras del alfabeto en orden y fuera de orden, y producirá el sonido asociado a 15 letras.",
  },
  {
    idObjetivo: "LE-4-6-LEC-M-01",
    nombreObjetivo: "Leer palabras bisílabas de alta frecuencia de forma global",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Lectura de palabras", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente leerá correctamente al menos 20 palabras bisílabas de alta frecuencia (casa, perro, mesa, niña) de forma global o decodificada con un 80 % de aciertos.",
  },
  {
    idObjetivo: "LE-4-6-ESC-B-01",
    nombreObjetivo: "Copiar su nombre y palabras simples con letra clara y orientada",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Escritura copiada", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El paciente copiará su nombre propio y 5 palabras simples con letras reconocibles, orientadas correctamente y dentro del renglón en el 80 % de los intentos.",
  },
  {
    idObjetivo: "LE-6-8-CON-M-01",
    nombreObjetivo: "Agregar, omitir y sustituir fonemas en palabras (manipulación fonémica)",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Conciencia fonémica avanzada", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente realizará tareas de omisión (silla sin /s/ = illa), sustitución (pala → bala) y adición de fonemas con un 80 % de aciertos en 20 ítems.",
  },
  {
    idObjetivo: "LE-6-8-LEC-M-01",
    nombreObjetivo: "Leer oraciones simples con comprensión literal",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Comprensión lectora", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente leerá oraciones de 6-10 palabras y responderá preguntas literales (quién, qué, dónde) con un 80 % de aciertos.",
  },
  {
    idObjetivo: "LE-6-8-LEC-M-02",
    nombreObjetivo: "Leer en voz alta con fluidez y precisión textos de nivel 1.º grado",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Fluidez lectora", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente leerá en voz alta textos adecuados a su nivel con menos del 5 % de errores de decodificación y una velocidad de al menos 40 palabras por minuto.",
  },
  {
    idObjetivo: "LE-6-8-ESC-M-01",
    nombreObjetivo: "Escribir oraciones simples con ortografía natural correcta",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Escritura de oraciones", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente escribirá oraciones de 5-7 palabras al dictado con mayúscula inicial, punto final y ortografía natural correcta (sin errores de correspondencia fonema-grafema) en el 80 % de los casos.",
  },
  {
    idObjetivo: "LE-6-8-ESC-A-01",
    nombreObjetivo: "Producir textos escritos breves con estructura narrativa",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Producción textual", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente escribirá un texto narrativo breve (mínimo 5 oraciones) con inicio, desarrollo y desenlace, con cohesión temática y ortografía natural aceptable.",
  },
  {
    idObjetivo: "LE-6-8-LEC-A-01",
    nombreObjetivo: "Comprender textos informativos respondiendo preguntas inferenciales",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Comprensión inferencial", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "Tras leer un texto informativo breve, el paciente responderá preguntas que requieran inferencia (por qué, qué habría pasado si, cuál es la idea principal) con un 75 % de aciertos.",
  },
  {
    idObjetivo: "LE-6-8-CON-A-01",
    nombreObjetivo: "Segmentar completamente palabras en fonemas y deletrearlas correctamente",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Segmentación fonémica", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "avanzado", estadoBanco: "activo",
    definicionOperativa: "El paciente segmentará palabras de 4-6 fonemas en sus componentes individuales y deletreará palabras familiares e inusales con un 80 % de precisión.",
  },
  {
    idObjetivo: "LE-4-6-ESC-M-01",
    nombreObjetivo: "Escribir palabras de 2-3 sílabas al dictado",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Escritura al dictado", franjaEtaria: "4-6", franjaEtariaMin: 4, franjaEtariaMax: 6,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente escribirá correctamente palabras de 2-3 sílabas dictadas por el terapeuta con un 75 % de aciertos, respetando la correspondencia fonema-grafema básica.",
  },
  {
    idObjetivo: "LE-6-8-ESC-M-02",
    nombreObjetivo: "Usar mayúsculas y puntuación básica en textos escritos",
    modulo: "Lectoescritura", area: "Lectoescritura", areaClinica: "lectoescritura",
    subarea: "Ortografía y puntuación", franjaEtaria: "6-8", franjaEtariaMin: 6, franjaEtariaMax: 8,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El paciente usará mayúsculas al inicio de oración y tras punto, más punto final y coma en enumeraciones simples, en el 80 % de las oraciones de sus producciones escritas.",
  },

  // ─────────────────────────────────────────────────────────────────────
  // ESTIMULACIÓN TEMPRANA (ET) — 16 goals
  // ─────────────────────────────────────────────────────────────────────
  {
    idObjetivo: "ET-0-2-AT-B-01",
    nombreObjetivo: "Mantener contacto visual con el cuidador durante el juego cara a cara",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Atención conjunta", franjaEtaria: "0-2", franjaEtariaMin: 0, franjaEtariaMax: 2,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño mantendrá contacto visual con el cuidador durante episodios de juego cara a cara por al menos 3 segundos continuos en el 70 % de las oportunidades presentadas.",
  },
  {
    idObjetivo: "ET-0-2-IMI-B-01",
    nombreObjetivo: "Imitar gestos faciales simples del adulto (sacar la lengua, abrir la boca)",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Imitación gestual", franjaEtaria: "0-2", franjaEtariaMin: 0, franjaEtariaMax: 2,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño imitará al menos 3 gestos faciales del adulto (sacar la lengua, sonrisa, abrir la boca) en el 70 % de las oportunidades durante el juego cara a cara.",
  },
  {
    idObjetivo: "ET-0-2-PRV-B-01",
    nombreObjetivo: "Vocalizar en respuesta a la voz del adulto (protoconversación)",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Comunicación preverbal", franjaEtaria: "0-2", franjaEtariaMin: 0, franjaEtariaMax: 2,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño responderá vocalmente al habla del adulto durante intercambios de protoconversación, alternando las vocalizaciones con las del adulto en el 70 % de las oportunidades.",
  },
  {
    idObjetivo: "ET-0-2-SEN-B-01",
    nombreObjetivo: "Responder a la estimulación táctil y auditiva del entorno",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Integración sensorial", franjaEtaria: "0-2", franjaEtariaMin: 0, franjaEtariaMax: 2,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño responderá con orientación de cabeza, expresión facial o movimiento corporal a estímulos auditivos (voz, música) y táctiles (texturas) presentados por el cuidador en el 75 % de las oportunidades.",
  },
  {
    idObjetivo: "ET-0-2-INT-B-01",
    nombreObjetivo: "Sonreír en respuesta a la voz y el rostro del cuidador principal",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Vínculo e interacción", franjaEtaria: "0-2", franjaEtariaMin: 0, franjaEtariaMax: 2,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño responderá con sonrisa social a la voz y el rostro del cuidador en el 75 % de las situaciones de interacción directa, sin estimulación táctil como única activadora.",
  },
  {
    idObjetivo: "ET-2-4-AT-B-01",
    nombreObjetivo: "Seguir la mirada del adulto para atender a un objeto de interés",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Seguimiento de mirada", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño seguirá la dirección de la mirada del adulto para localizar un objeto en el campo visual en el 75 % de los intentos, sin que el adulto señale con el dedo.",
  },
  {
    idObjetivo: "ET-2-4-IMI-B-01",
    nombreObjetivo: "Imitar acciones con objetos durante el juego funcional",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Imitación de acciones", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño imitará 5 acciones con objetos (empujar un carro, darle de comer a un muñeco, apilar bloques) demostradas por el adulto con un 80 % de fidelidad en el gesto imitado.",
  },
  {
    idObjetivo: "ET-2-4-JUE-B-01",
    nombreObjetivo: "Participar en juego funcional con objetos: usar cada objeto según su función",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Juego funcional", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño usará al menos 5 objetos según su función convencional (cuchara para comer, teléfono para hablar, cepillo para peinar) de forma espontánea durante el juego.",
  },
  {
    idObjetivo: "ET-2-4-JUE-M-01",
    nombreObjetivo: "Desarrollar juego simbólico simple con muñecos y figuras",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Juego simbólico", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El niño realizará secuencias de 2-3 acciones simbólicas con muñecos (darle de comer, acostarlos, bañarlos) de forma espontánea durante el juego libre en la sesión.",
  },
  {
    idObjetivo: "ET-2-4-COM-B-01",
    nombreObjetivo: "Comprender palabras de uso cotidiano en el contexto familiar",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Comprensión léxica temprana", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño señalará o irá hacia el objeto/persona nombrado por el adulto (leche, mamá, zapato, pelota) en el 80 % de las oportunidades dentro del contexto familiar cotidiano.",
  },
  {
    idObjetivo: "ET-2-4-PRV-B-01",
    nombreObjetivo: "Producir primeras palabras con intención comunicativa clara",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Primeras palabras", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño producirá al menos 10 palabras distintas de forma consistente y con intención comunicativa (nombrar, pedir, rechazar) en contextos espontáneos, según reporte del familiar.",
  },
  {
    idObjetivo: "ET-2-4-VIN-B-01",
    nombreObjetivo: "Buscar consuelo y regulación emocional activamente con el cuidador",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Vínculo de apego", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño buscará activamente al cuidador ante situaciones de malestar (llanto, miedo) acercándose físicamente o llamándolo verbalmente en el 80 % de las situaciones de estrés observadas.",
  },
  {
    idObjetivo: "ET-2-4-SEN-B-01",
    nombreObjetivo: "Tolerar texturas y sensaciones táctiles variadas durante el juego",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Procesamiento sensorial", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "básico", estadoBanco: "activo",
    definicionOperativa: "El niño tolerará explorar materiales de texturas variadas (arena, plastilina, materiales suaves y rugosos) durante al menos 5 minutos sin conductas de rechazo intensas, según observación del terapeuta.",
  },
  {
    idObjetivo: "ET-2-4-COM-M-01",
    nombreObjetivo: "Comprender preguntas simples (¿qué es? ¿dónde está?) sin apoyo gestual",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Comprensión de preguntas", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El niño responderá apropiadamente a preguntas simples (¿qué es esto? ¿dónde está la pelota?) señalando o nombrando, en el 75 % de los intentos sin que el adulto use gestos.",
  },
  {
    idObjetivo: "ET-2-4-JUE-M-02",
    nombreObjetivo: "Participar en juego de roles simples con un adulto",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Juego de roles", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El niño asumirá un rol en un juego simbólico con el adulto (cocinar, ser médico, ir de compras) realizando al menos 3 acciones de rol diferentes de forma espontánea.",
  },
  {
    idObjetivo: "ET-2-4-AT-M-01",
    nombreObjetivo: "Coordinar atención entre el adulto y el objeto de manera triádica",
    modulo: "Estimulación Temprana", area: "Estimulación Temprana", areaClinica: "estimulación temprana",
    subarea: "Atención conjunta triádica", franjaEtaria: "2-4", franjaEtariaMin: 2, franjaEtariaMax: 4,
    nivelDificultad: "intermedio", estadoBanco: "activo",
    definicionOperativa: "El niño alternará la mirada entre el adulto y el objeto de juego para compartir el interés, haciendo al menos 3 turnos de alternancia de mirada por episodio de juego compartido.",
  },
];

async function main() {
  console.log("🌱 Seeding extended goal library...");

  const existing = await db.select({ idObjetivo: goalLibraryTable.idObjetivo }).from(goalLibraryTable);
  const existingCodes = new Set(existing.map(r => r.idObjetivo));

  const toInsert = GOALS.filter(g => !existingCodes.has(g.idObjetivo));
  const skipped  = GOALS.filter(g =>  existingCodes.has(g.idObjetivo));

  if (skipped.length > 0) {
    console.log(`⚠️  Skipping ${skipped.length} goals already in DB: ${skipped.map(g => g.idObjetivo).join(", ")}`);
  }

  if (toInsert.length === 0) {
    console.log("✅ All goals already exist. Nothing to insert.");
    return;
  }

  const CHUNK_SIZE = 20;
  let inserted = 0;
  for (let i = 0; i < toInsert.length; i += CHUNK_SIZE) {
    const chunk = toInsert.slice(i, i + CHUNK_SIZE);
    await db.insert(goalLibraryTable).values(chunk.map(g => ({
      idObjetivo:       g.idObjetivo,
      nombreObjetivo:   g.nombreObjetivo,
      modulo:           g.modulo,
      area:             g.area,
      areaClinica:      g.areaClinica,
      subarea:          g.subarea,
      franjaEtaria:     g.franjaEtaria,
      franjaEtariaMin:  g.franjaEtariaMin,
      franjaEtariaMax:  g.franjaEtariaMax,
      nivelDificultad:  g.nivelDificultad,
      estadoBanco:      g.estadoBanco,
      definicionOperativa: g.definicionOperativa,
    })));
    inserted += chunk.length;
    console.log(`  ✅ Inserted ${inserted}/${toInsert.length} goals...`);
  }

  // Final summary
  const total = await db.select({ idObjetivo: goalLibraryTable.idObjetivo }).from(goalLibraryTable);
  const areaCount = await db
    .selectDistinct({ area: goalLibraryTable.area })
    .from(goalLibraryTable);

  console.log("\n── Seed complete ──────────────────────────────");
  console.log(`📚 Table updated:   goal_library`);
  console.log(`➕ Goals inserted:  ${inserted}`);
  console.log(`📊 Total in DB:     ${total.length}`);
  console.log(`🗂️  Areas covered:   ${areaCount.map(r => r.area).sort().join(", ")}`);
  console.log("────────────────────────────────────────────────");
}

main().catch(e => { console.error(e); process.exit(1); });
