import { db } from "@workspace/db";
import { goalLibraryTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const goals = [
  // ─── LENGUAJE ────────────────────────────────────────────────────────────────
  {
    idObjetivo: "NL-001",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Léxico",
    franjaEtaria: "2-4",
    franjaEtariaMin: 2,
    franjaEtariaMax: 4,
    nivelDificultad: "básico",
    nombreObjetivo: "Ampliar el vocabulario expresivo en contexto funcional",
    definicionOperativa: "El/la paciente incrementará su léxico expresivo nominando correctamente objetos, personas y acciones de su entorno cotidiano, en situaciones espontáneas y estructuradas.",
    actividadesClinicas: "Juegos de denominación con tarjetas temáticas. Rutinas de nombrar objetos del entorno clínico. Juego simbólico con vocabulario dirigido. Láminas de categorías semánticas.",
    actividadesFamilia: "Nombrar objetos del hogar durante las comidas. Nombrar ropa al vestirse. Leer cuentos con imágenes señalando y nombrando. Juego del 'qué es esto' durante el baño.",
    habilidadesRelacionadas: "Atención compartida, memoria semántica, imitación",
    prerequisitos: "Comprensión de al menos 50 palabras, intención comunicativa presente",
    metaPorcentaje: "80% en 4 de 5 oportunidades",
    intentosSugeridos: "10 por sesión",
    recomendacionClinica: "Contextualizar el vocabulario en rutinas del hogar. Evitar correcciones directas; modelar la forma correcta.",
    indicadorTipo: "Denominación espontánea",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-002",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Morfosintaxis",
    franjaEtaria: "2-4",
    franjaEtariaMin: 2,
    franjaEtariaMax: 4,
    nivelDificultad: "básico",
    nombreObjetivo: "Producir oraciones simples de estructura sujeto-verbo-objeto",
    definicionOperativa: "El/la paciente producirá oraciones simples de 3 o más palabras con estructura SVO en respuesta a preguntas y en situaciones de narración espontánea.",
    actividadesClinicas: "Modelado de oraciones durante el juego. Expansiones lingüísticas. Narración de láminas de acción. Completar frases con apoyo visual.",
    actividadesFamilia: "Preguntar '¿qué está haciendo?' al mirar cuentos. Expandir las frases del niño añadiendo sujeto o complemento. Describir lo que hacen juntos durante actividades diarias.",
    habilidadesRelacionadas: "Vocabulario expresivo básico (NL-001), comprensión de acciones",
    prerequisitos: "Léxico de al menos 50 palabras, algunas combinaciones de dos palabras espontáneas",
    metaPorcentaje: "75% de oportunidades en 3 sesiones consecutivas",
    intentosSugeridos: "8 por sesión",
    recomendacionClinica: "Usar expansiones y recasts. No exigir repetición; modelar de forma natural en el juego.",
    indicadorTipo: "Muestra de lenguaje espontáneo",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-003",
    modulo: "Neurolengua",
    area: "Lenguaje Comprensivo-Expresivo",
    areaClinica: "lenguaje",
    subarea: "Comprensión",
    franjaEtaria: "4-7",
    franjaEtariaMin: 4,
    franjaEtariaMax: 7,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Comprender y ejecutar instrucciones de dos o más pasos",
    definicionOperativa: "El/la paciente comprenderá instrucciones verbales que incluyan 2 o más acciones secuenciadas, sin apoyo gestual del examinador.",
    actividadesClinicas: "Instrucciones durante actividades de juego. Seguimiento de consignas en tareas de papel. Juegos de roles con instrucciones encadenadas. Actividades de cocina o construcción.",
    actividadesFamilia: "Dar instrucciones cotidianas en dos pasos ('agarra tu mochila y ponla en la silla'). Juego de 'Simón dice' con dos acciones. Rutinas con pasos explícitos.",
    habilidadesRelacionadas: "Memoria de trabajo, atención auditiva, comprensión de vocabulario",
    prerequisitos: "Comprensión de instrucciones de un paso con 90% de éxito",
    metaPorcentaje: "80% en 4 de 5 oportunidades",
    intentosSugeridos: "6 por sesión",
    recomendacionClinica: "Verificar que no haya dificultades auditivas. Comenzar con instrucciones de contenido familiar.",
    indicadorTipo: "Ejecución conductual",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-004",
    modulo: "Neurolengua",
    area: "Lenguaje Narrativo",
    areaClinica: "lenguaje",
    subarea: "Narrativo",
    franjaEtaria: "4-8",
    franjaEtariaMin: 4,
    franjaEtariaMax: 8,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Narrar eventos con estructura temporal coherente",
    definicionOperativa: "El/la paciente narrará eventos pasados o cuentos con al menos 5 proposiciones ordenadas temporalmente, incluyendo inicio, desarrollo y cierre.",
    actividadesClinicas: "Renarración de cuentos con apoyo de secuencias de imágenes. Narración de eventos propios. Uso de organizadores visuales de historia. Grabación y escucha de sus narraciones.",
    actividadesFamilia: "Pedir al niño que cuente cómo fue su día escolar. Leer y luego preguntar '¿qué pasó primero, después y al final?'. Armar álbumes de fotos narrando lo ocurrido.",
    habilidadesRelacionadas: "Memoria episódica, conectores temporales, vocabulario de tiempo",
    prerequisitos: "Oraciones de 3+ palabras (NL-002), secuencias de 3 elementos",
    metaPorcentaje: "Narración con 5+ proposiciones coherentes en 3 de 4 muestras",
    intentosSugeridos: "2-3 narrativas por sesión",
    recomendacionClinica: "Usar preguntas facilitadoras, no interrumpir. Registrar longitud y coherencia del relato.",
    indicadorTipo: "Análisis narrativo",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-005",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Conectores",
    franjaEtaria: "6-10",
    franjaEtariaMin: 6,
    franjaEtariaMax: 10,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Usar conectores causales y temporales en discurso oral",
    definicionOperativa: "El/la paciente usará de forma apropiada conectores causales (porque, ya que, por eso) y temporales (primero, después, finalmente) en su producción oral espontánea y estructurada.",
    actividadesClinicas: "Completar oraciones con conectores. Explicar causas de eventos. Narrar con apoyo de conectores escritos en tarjetas. Análisis de cuentos señalando conectores.",
    actividadesFamilia: "Preguntar '¿por qué crees que pasó eso?' al leer cuentos. Armar secuencias de acciones con palabras de orden (primero, luego, por último).",
    habilidadesRelacionadas: "Narrativo (NL-004), razonamiento causal, planificación del discurso",
    prerequisitos: "Narración básica (NL-004), comprensión de causa-efecto",
    metaPorcentaje: "80% de uso correcto en muestra de discurso",
    intentosSugeridos: "5 por sesión",
    recomendacionClinica: "Trabajar primero temporales, luego causales. Usar actividades de causalidad física antes de social.",
    indicadorTipo: "Análisis de discurso",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-006",
    modulo: "Neurolengua",
    area: "Semántica",
    areaClinica: "lenguaje",
    subarea: "Semántica",
    franjaEtaria: "7-12",
    franjaEtariaMin: 7,
    franjaEtariaMax: 12,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Comprender y producir lenguaje figurado (metáforas, refranes)",
    definicionOperativa: "El/la paciente identificará el significado no literal de expresiones idiomáticas, metáforas y refranes frecuentes del español, y podrá explicarlos con sus propias palabras.",
    actividadesClinicas: "Presentación de refranes con explicación contextual. Juegos de adivinanza con metáforas. Lectura de textos con lenguaje figurado. Creación propia de metáforas sencillas.",
    actividadesFamilia: "Comentar el significado de refranes cotidianos. Identificar metáforas en canciones o películas. Juego de 'adivina qué quiere decir'.",
    habilidadesRelacionadas: "Teoría de la mente, inferencias, conocimiento cultural",
    prerequisitos: "Comprensión literal robusta, vocabulario amplio",
    metaPorcentaje: "75% de comprensión en 10 expresiones presentadas",
    intentosSugeridos: "5-6 por sesión",
    recomendacionClinica: "Comenzar con expresiones de alta frecuencia en el contexto cultural del paciente.",
    indicadorTipo: "Comprensión y explicación verbal",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-007",
    modulo: "Neurolengua",
    area: "Léxico",
    areaClinica: "lenguaje",
    subarea: "Categorías semánticas",
    franjaEtaria: "3-6",
    franjaEtariaMin: 3,
    franjaEtariaMax: 6,
    nivelDificultad: "básico",
    nombreObjetivo: "Clasificar objetos en categorías semánticas básicas",
    definicionOperativa: "El/la paciente agrupará objetos en categorías semánticas (animales, alimentos, ropa, muebles, transportes) señalando o nombrando al menos 4 elementos por categoría.",
    actividadesClinicas: "Juegos de clasificación con tarjetas. Identificar el intruso en una categoría. Dominó temático. Asociación de imágenes por categorías.",
    actividadesFamilia: "Juego de 'busca todas las cosas de comer'. Ordenar la compra por categorías. Clasificar juguetes por tipo. Mirar libros temáticos juntos.",
    habilidadesRelacionadas: "Memoria semántica, atención selectiva, razonamiento por similitud",
    prerequisitos: "Vocabulario expresivo de 50+ palabras (NL-001)",
    metaPorcentaje: "4+ ítems por categoría en el 80% de las sesiones",
    intentosSugeridos: "3 categorías por sesión",
    recomendacionClinica: "Comenzar con categorías de alta frecuencia (alimentos, animales). Usar objetos reales antes que imágenes.",
    indicadorTipo: "Clasificación y denominación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-008",
    modulo: "Neurolengua",
    area: "Lenguaje Comprensivo-Expresivo",
    areaClinica: "lenguaje",
    subarea: "Morfología",
    franjaEtaria: "4-8",
    franjaEtariaMin: 4,
    franjaEtariaMax: 8,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Usar correctamente la concordancia de género y número",
    definicionOperativa: "El/la paciente producirá sintagmas nominales con concordancia correcta de género (el/la, un/una) y número (singular/plural) en al menos el 80% de sus producciones.",
    actividadesClinicas: "Corrección implícita de concordancias. Juegos de 'uno y muchos'. Descripciones de láminas corrigiendo errores. Completar oraciones con determinantes.",
    actividadesFamilia: "Señalar diferencias entre uno y varios objetos. Cantar canciones con plurales. Contar objetos enfatizando el plural.",
    habilidadesRelacionadas: "Morfosintaxis, oraciones SVO (NL-002), memoria de trabajo",
    prerequisitos: "Combinaciones de dos palabras, vocabulario nominal básico",
    metaPorcentaje: "80% de concordancias correctas en muestra de habla",
    intentosSugeridos: "10 ítems por sesión",
    recomendacionClinica: "Usar recasts naturales; no corrección directa. Registrar en muestra de lenguaje espontáneo.",
    indicadorTipo: "Análisis morfológico de muestra",
    estadoBanco: "activo",
  },

  // ─── HABLA ───────────────────────────────────────────────────────────────────
  {
    idObjetivo: "HA-001",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Articulación",
    franjaEtaria: "2-5",
    franjaEtariaMin: 2,
    franjaEtariaMax: 5,
    nivelDificultad: "básico",
    nombreObjetivo: "Producir fonemas oclusivos y nasales en posición inicial de palabra",
    definicionOperativa: "El/la paciente producirá los fonemas /p/, /b/, /t/, /d/, /k/, /g/, /m/, /n/ en posición inicial de sílaba en palabras aisladas y en frases cortas con un 80% de precisión.",
    actividadesClinicas: "Ejercicios de imitación de sílabas. Juego de denominación con palabras que inician con el fonema objetivo. Canciones y rimas. Pares mínimos.",
    actividadesFamilia: "Leer libros con aliteración. Cantar canciones con el sonido objetivo. Nombrar imágenes del fonema trabajado cada día.",
    habilidadesRelacionadas: "Discriminación auditiva (HA-005), praxis oromotora (MO-002), imitación",
    prerequisitos: "Discriminación auditiva de fonemas trabajados, función motora oral adecuada",
    metaPorcentaje: "80% de producción correcta en palabras aisladas",
    intentosSugeridos: "20 producciones por sesión",
    recomendacionClinica: "No corregir en habla espontánea; reforzar en actividades dirigidas. Verificar audición normal.",
    indicadorTipo: "Producción articulatoria",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-002",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Procesos fonológicos",
    franjaEtaria: "3-6",
    franjaEtariaMin: 3,
    franjaEtariaMax: 6,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Reducir procesos de simplificación fonológica (sustitución y omisión)",
    definicionOperativa: "El/la paciente reducirá los procesos de sustitución y omisión de fonemas en posiciones media y final de palabra, mejorando la estructura silábica CVC y CCVC.",
    actividadesClinicas: "Análisis de errores fonológicos con retroalimentación visual. Mínimos pares con significado. Ejercicios de segmentación silábica. Bombardeo auditivo.",
    actividadesFamilia: "Leer en voz alta lentamente, modelando la palabra correcta. Juego de 'repite cómo yo lo digo'. Escuchar audios de palabras objetivo.",
    habilidadesRelacionadas: "Discriminación auditiva (HA-005), articulación básica (HA-001), conciencia fonológica",
    prerequisitos: "Discriminación auditiva de pares mínimos, articulación de fonemas en posición inicial",
    metaPorcentaje: "Reducción del 50% en errores respecto al baseline en 8 semanas",
    intentosSugeridos: "15 palabras objetivo por sesión",
    recomendacionClinica: "Priorizar fonemas de adquisición temprana. Usar feedback visual (espejo, app de feedback).",
    indicadorTipo: "Análisis de errores fonológicos",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-003",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Inteligibilidad",
    franjaEtaria: "4-7",
    franjaEtariaMin: 4,
    franjaEtariaMax: 7,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Mejorar la inteligibilidad del habla espontánea",
    definicionOperativa: "El/la paciente aumentará su porcentaje de inteligibilidad en habla espontánea con interlocutores no familiares del 50% al 80% o más.",
    actividadesClinicas: "Juegos de descripción sin apoyo visual para el interlocutor. Grabaciones y análisis de inteligibilidad. Práctica en situaciones comunicativas reales. Técnicas de desaceleración del habla.",
    actividadesFamilia: "No anticipar lo que el niño quiere decir; esperar que se exprese. Pedir aclaraciones de forma natural. Pedir que repita usando estrategias aprendidas.",
    habilidadesRelacionadas: "Articulación (HA-001), procesos fonológicos (HA-002), velocidad del habla",
    prerequisitos: "Articulación de fonemas objetivo en palabras aisladas",
    metaPorcentaje: "80% de inteligibilidad con interlocutor no familiar",
    intentosSugeridos: "Muestra de 50 palabras por sesión",
    recomendacionClinica: "Calcular % de inteligibilidad con interlocutor ciego. Considerar examen auditivo periódico.",
    indicadorTipo: "Ratio de inteligibilidad",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-004",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Fluidez",
    franjaEtaria: "6-12",
    franjaEtariaMin: 6,
    franjaEtariaMax: 12,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Reducir disfluencias e implementar técnicas de fluidez",
    definicionOperativa: "El/la paciente aplicará técnicas de control de fluidez (arranque suave, habla fluida, control de velocidad) reduciendo el porcentaje de sílabas disfluentes por debajo del 3% en conversación.",
    actividadesClinicas: "Entrenamiento en respiración abdominal. Técnica de habla fluida y arranque suave. Práctica de habla en diferentes contextos. Desensibilización a disfluencias.",
    actividadesFamilia: "Mantener contacto visual y escuchar sin interrumpir. No terminar las frases del niño. Hablar con ritmo pausado. Reducir preguntas directas en situaciones de alta demanda.",
    habilidadesRelacionadas: "Coordinación fonorrespiratoria (MO-003), control atencional, manejo de ansiedad",
    prerequisitos: "Motivación para el tratamiento, diagnóstico de tartamudez confirmado",
    metaPorcentaje: "< 3% de sílabas disfluentes en conversación espontánea",
    intentosSugeridos: "Muestras de 300 sílabas por sesión",
    recomendacionClinica: "Involucrar a la familia en el tratamiento. Coordinar con la escuela. Trabajar la actitud hacia la tartamudez.",
    indicadorTipo: "Porcentaje de sílabas disfluentes",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-005",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Discriminación auditiva",
    franjaEtaria: "3-6",
    franjaEtariaMin: 3,
    franjaEtariaMax: 6,
    nivelDificultad: "básico",
    nombreObjetivo: "Discriminar auditivamente pares mínimos de fonemas",
    definicionOperativa: "El/la paciente discriminará de forma auditiva pares mínimos que difieran en un único rasgo fonológico (ej. /p/-/b/, /t/-/d/, /s/-/z/) con un 80% de acierto.",
    actividadesClinicas: "Juegos de 'señala cuál escuchas'. Pares mínimos con imágenes. Bombardeo auditivo. Clasificación de palabras por sonido inicial.",
    actividadesFamilia: "Juego de 'adivina qué palabra dije'. Canciones con pares de palabras similares. Leer rimas y señalar palabras que suenan parecido.",
    habilidadesRelacionadas: "Memoria auditiva, atención sostenida, procesamiento fonológico",
    prerequisitos: "Audición dentro de parámetros normales (descartar hipoacusia)",
    metaPorcentaje: "80% de discriminaciones correctas",
    intentosSugeridos: "20 pares por sesión",
    recomendacionClinica: "Descartar hipoacusia antes de iniciar. Comenzar con pares de alta frecuencia.",
    indicadorTipo: "Discriminación auditiva con imagen",
    estadoBanco: "activo",
  },

  // ─── PRAGMÁTICA ───────────────────────────────────────────────────────────────
  {
    idObjetivo: "PR-001",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Comunicación no verbal",
    franjaEtaria: "2-5",
    franjaEtariaMin: 2,
    franjaEtariaMax: 5,
    nivelDificultad: "básico",
    nombreObjetivo: "Mantener contacto visual durante el intercambio comunicativo",
    definicionOperativa: "El/la paciente mantendrá contacto visual con su interlocutor durante al menos el 50% del tiempo de conversación o juego compartido.",
    actividadesClinicas: "Juegos cara a cara con objeto de interés. Rutinas con atención conjunta. Juego del espejo. Actividades interactivas que requieran mirar al otro.",
    actividadesFamilia: "Ponerse a la altura del niño al hablarle. Usar juegos de 'míranos'. Esperar el contacto visual antes de dar lo que pide.",
    habilidadesRelacionadas: "Atención conjunta, gestos comunicativos (PR-004), regulación sensorial",
    prerequisitos: "Ninguno obligatorio; adaptar a perfil sensorial",
    metaPorcentaje: "50% del tiempo de interacción con mirada social",
    intentosSugeridos: "Observar en 10 minutos de juego libre",
    recomendacionClinica: "No forzar el contacto visual directo; propiciar situaciones naturales. Considerar perfil sensorial.",
    indicadorTipo: "Observación en juego",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-002",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Conversación",
    franjaEtaria: "3-6",
    franjaEtariaMin: 3,
    franjaEtariaMax: 6,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Respetar los turnos conversacionales",
    definicionOperativa: "El/la paciente respetará los turnos en intercambios conversacionales con el/la profesional y con pares, esperando su turno para hablar en al menos el 80% de las oportunidades.",
    actividadesClinicas: "Juegos de turnos con objeto símbolo. Conversaciones estructuradas con señal visual de turno. Role-play de situaciones cotidianas. Juegos de mesa con turno explícito.",
    actividadesFamilia: "Hablar en familia respetando el turno de cada uno. Usar una 'pelota de hablar'. Juegos de mesa que requieran respetar turnos.",
    habilidadesRelacionadas: "Contacto visual (PR-001), inhibición de respuesta, escucha activa",
    prerequisitos: "Intención comunicativa presente, comprensión de reglas simples",
    metaPorcentaje: "80% de turnos respetados en intercambio de 10 minutos",
    intentosSugeridos: "Observar en conversación libre",
    recomendacionClinica: "Usar señales visuales (luz, tarjeta) al inicio del tratamiento. Reducir apoyos gradualmente.",
    indicadorTipo: "Observación en interacción",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-003",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Habilidades conversacionales",
    franjaEtaria: "5-10",
    franjaEtariaMin: 5,
    franjaEtariaMax: 10,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Iniciar y mantener tópicos de conversación de forma apropiada",
    definicionOperativa: "El/la paciente iniciará temas de conversación relevantes y los mantendrá por al menos 4 intercambios, realizando preguntas y comentarios apropiados al contexto.",
    actividadesClinicas: "Scripts conversacionales con temas de interés. Role-play de situaciones sociales. Análisis de conversaciones grabadas. Juego de 'seguir el tema'.",
    actividadesFamilia: "Conversar en familia sobre temas del interés del niño. Modelar cómo añadir información a un tema. Evitar respuestas monosilábicas.",
    habilidadesRelacionadas: "Turnos (PR-002), conocimiento del mundo, memoria de trabajo",
    prerequisitos: "Respeto de turnos (PR-002), repertorio léxico funcional",
    metaPorcentaje: "Mantiene tópico 4+ intercambios en el 75% de las situaciones",
    intentosSugeridos: "3 situaciones conversacionales por sesión",
    recomendacionClinica: "Usar temas de alta motivación para el paciente. Trabajar en grupo pequeño cuando sea posible.",
    indicadorTipo: "Análisis de conversación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-004",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Comunicación intencional",
    franjaEtaria: "1-3",
    franjaEtariaMin: 1,
    franjaEtariaMax: 3,
    nivelDificultad: "básico",
    nombreObjetivo: "Usar gestos comunicativos intencionales (señalar, mostrar, dar)",
    definicionOperativa: "El/la paciente usará gestos deícticos y referenciales (señalar con el índice, mostrar objetos, dar objetos) de forma intencional para comunicar deseos y compartir referentes.",
    actividadesClinicas: "Juego con objetos de alta motivación fuera de alcance. Modelado de gesto de señalar. Actividades de atención conjunta. Rutinas de 'dame/toma'.",
    actividadesFamilia: "Modelar el gesto de señalar en rutinas. Esperar el gesto antes de dar el objeto deseado. Leer cuentos señalando imágenes juntos.",
    habilidadesRelacionadas: "Atención conjunta, imitación social, contacto visual (PR-001)",
    prerequisitos: "Ninguno — es un objetivo pre-verbal/temprano",
    metaPorcentaje: "Usa 3 gestos comunicativos diferentes en sesión de juego",
    intentosSugeridos: "Observar en 15 minutos de juego",
    recomendacionClinica: "Trabajar en contextos altamente motivantes. Evitar anticipar todas las necesidades del niño.",
    indicadorTipo: "Inventario de gestos comunicativos",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-005",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Adaptación discursiva",
    franjaEtaria: "6-12",
    franjaEtariaMin: 6,
    franjaEtariaMax: 12,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Adaptar el registro comunicativo al interlocutor y contexto",
    definicionOperativa: "El/la paciente ajustará su lenguaje (vocabulario, tono, formalidad) según las características del interlocutor (adulto/niño, conocido/desconocido) y el contexto (formal/informal).",
    actividadesClinicas: "Role-play con diferentes interlocutores. Análisis de situaciones comunicativas. Comparar formas de hablar en distintos contextos. Grabación y autoevaluación.",
    actividadesFamilia: "Modelar diferencias de registro en la vida diaria. Señalar cómo hablan los personajes en películas según con quién hablan.",
    habilidadesRelacionadas: "Teoría de la mente, habilidades conversacionales (PR-003), metacognición",
    prerequisitos: "Habilidades conversacionales básicas (PR-003), lenguaje fluido",
    metaPorcentaje: "Ajuste apropiado en 3 de 4 situaciones de role-play",
    intentosSugeridos: "4 situaciones contrastadas por sesión",
    recomendacionClinica: "Trabajar con situaciones reales del entorno del paciente. Reforzar autoevaluación.",
    indicadorTipo: "Role-play y autoevaluación",
    estadoBanco: "activo",
  },

  // ─── MOTRICIDAD OROFACIAL ─────────────────────────────────────────────────────
  {
    idObjetivo: "MO-001",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Tono muscular",
    franjaEtaria: "2-6",
    franjaEtariaMin: 2,
    franjaEtariaMax: 6,
    nivelDificultad: "básico",
    nombreObjetivo: "Mejorar el tono muscular labial y lingual",
    definicionOperativa: "El/la paciente incrementará el tono y la fuerza muscular de labios y lengua mediante ejercicios de resistencia y estimulación, observando mejora en la postura de reposo y en la articulación.",
    actividadesClinicas: "Masajes de estimulación labial y lingual. Ejercicios de soplo y succión con resistencia. Vibración táctil. Comer alimentos de diferentes texturas. Ejercicios con espátula.",
    actividadesFamilia: "Masajes faciales suaves en rutinas de higiene. Ofrecer alimentos de distintas texturas. Ejercicios de soplo lúdico (velas, molinillos).",
    habilidadesRelacionadas: "Praxis oromotora (MO-002), deglución, articulación (HA-001)",
    prerequisitos: "Ninguno — es base para otros objetivos orofaciales",
    metaPorcentaje: "Tono adecuado en reposo observado por el profesional en 3 sesiones consecutivas",
    intentosSugeridos: "10 repeticiones de cada ejercicio",
    recomendacionClinica: "Evitar ejercicios sin función comunicativa. Integrar con objetivos articulatorios.",
    indicadorTipo: "Evaluación clínica de tono",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-002",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Praxis",
    franjaEtaria: "2-5",
    franjaEtariaMin: 2,
    franjaEtariaMax: 5,
    nivelDificultad: "básico",
    nombreObjetivo: "Realizar praxis orofaciales básicas bajo consigna verbal e imitación",
    definicionOperativa: "El/la paciente ejecutará al menos 6 praxis orofaciales básicas (abrir boca, sacar lengua, labios juntos, sonrisa, fruncir labios, soplar) ante consigna verbal y/o modelado.",
    actividadesClinicas: "Imitación frente al espejo. Juego de 'caras y gestos'. Uso de soplo lúdico. Modelado de praxis en secuencia. Fotos de referencia para praxis.",
    actividadesFamilia: "Juego del espejo en casa. Soplar velas o molinetes. Imitar caras de animales o personajes. Juegos de soplo con burbujas.",
    habilidadesRelacionadas: "Tono muscular (MO-001), imitación motora, atención",
    prerequisitos: "Tono mínimo adecuado para movilidad (MO-001)",
    metaPorcentaje: "6 de 8 praxis correctas en 3 sesiones consecutivas",
    intentosSugeridos: "5 repeticiones de cada praxis",
    recomendacionClinica: "Comenzar con imitación visual antes de consigna verbal. Incluir praxis en contextos lúdicos.",
    indicadorTipo: "Evaluación de praxis imitativa",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-003",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Respiración",
    franjaEtaria: "3-7",
    franjaEtariaMin: 3,
    franjaEtariaMax: 7,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Establecer patrón respiratorio nasal-oral coordinado con el habla",
    definicionOperativa: "El/la paciente adoptará un patrón respiratorio adecuado al habla: inspiración nasal, espiración oral controlada, con pausas apropiadas en el discurso.",
    actividadesClinicas: "Conciencia de la respiración. Ejercicios de soplo controlado. Habla con control respiratorio en frases cortas, luego largas. Coordinación fonorrespiratoria.",
    actividadesFamilia: "Practicar soplos lentos y largos en casa. Cantar con el niño enfatizando la respiración. Actividades de relajación con foco en la respiración.",
    habilidadesRelacionadas: "Tono muscular (MO-001), fluidez (HA-004), voz",
    prerequisitos: "Praxis básicas (MO-002), ausencia de obstrucción nasal crónica",
    metaPorcentaje: "Patrón respiratorio nasal de reposo en 3 de 4 sesiones observadas",
    intentosSugeridos: "5 series de soplo en cada sesión",
    recomendacionClinica: "Derivar a ORL si hay obstrucción nasal evidente. Coordinar con fonoaudiología de voz si hay disfonía asociada.",
    indicadorTipo: "Observación clínica de patrón respiratorio",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-004",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Deglución",
    franjaEtaria: "2-8",
    franjaEtariaMin: 2,
    franjaEtariaMax: 8,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Normalizar el patrón de deglución atípica",
    definicionOperativa: "El/la paciente realizará la deglución con adecuada postura lingual (no interposición), labios sellados y sin movimientos compensatorios visibles.",
    actividadesClinicas: "Ejercicios de elevación lingual. Técnica de deglución con posicionamiento correcto. Trabajo con diferentes consistencias. Biofeedback visual con espejo.",
    actividadesFamilia: "Recordar postura correcta al comer. Ofrecer alimentos que estimulen la deglución correcta. Seguimiento del programa de ejercicios indicado.",
    habilidadesRelacionadas: "Tono muscular (MO-001), praxis (MO-002), musculatura perioral",
    prerequisitos: "Evaluación de deglución completada, descarte de problemas estructurales",
    metaPorcentaje: "Deglución correcta en el 80% de los intentos observados",
    intentosSugeridos: "15 degluciones observadas por sesión",
    recomendacionClinica: "Coordinar con odontología y ortodoncia si hay maloclusión asociada. Trabajar en contexto de alimentación real.",
    indicadorTipo: "Observación de deglución",
    estadoBanco: "activo",
  },

  // ─── LECTOESCRITURA ────────────────────────────────────────────────────────────
  {
    idObjetivo: "LE-001",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Conciencia fonológica",
    franjaEtaria: "4-7",
    franjaEtariaMin: 4,
    franjaEtariaMax: 7,
    nivelDificultad: "básico",
    nombreObjetivo: "Desarrollar conciencia fonológica: rimas, sílabas y fonemas iniciales",
    definicionOperativa: "El/la paciente identificará rimas entre palabras, segmentará palabras en sílabas y reconocerá el fonema inicial de palabras presentadas oral o visualmente.",
    actividadesClinicas: "Juegos de rimas y adivinanzas. Palmadas para contar sílabas. Ordenar palabras por sonido inicial. Juegos de 'empieza con...'.",
    actividadesFamilia: "Cantar canciones con rimas. Contar sílabas dando palmadas al caminar. Buscar palabras que empiecen con el mismo sonido.",
    habilidadesRelacionadas: "Discriminación auditiva (HA-005), memoria fonológica, vocabulario",
    prerequisitos: "Discriminación de pares mínimos (HA-005), vocabulario receptivo de 100+ palabras",
    metaPorcentaje: "80% en tareas de rima, segmentación silábica e identificación de fonema inicial",
    intentosSugeridos: "10 ítems por habilidad por sesión",
    recomendacionClinica: "Trabajar conciencia silábica antes que fonémica. Usar materiales visuales de apoyo.",
    indicadorTipo: "Tareas de conciencia fonológica",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-002",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Lectura",
    franjaEtaria: "5-8",
    franjaEtariaMin: 5,
    franjaEtariaMax: 8,
    nivelDificultad: "básico",
    nombreObjetivo: "Decodificar palabras regulares con precisión",
    definicionOperativa: "El/la paciente leerá en voz alta palabras regulares (CVCV, CVC) sin errores de sustitución, omisión o inversión de grafemas, con una precisión mínima del 80%.",
    actividadesClinicas: "Lectura de listas de palabras regulares. Tarjetas de sílabas directas. Juego de dominó de sílabas. Lectura con seguimiento digital.",
    actividadesFamilia: "Leer cuentos simples juntos. Practicar con tarjetas de palabras. Señalar palabras conocidas en el entorno.",
    habilidadesRelacionadas: "Conciencia fonológica (LE-001), correspondencia grafema-fonema, memoria visual",
    prerequisitos: "Conciencia fonológica básica (LE-001), reconocimiento de letras del alfabeto",
    metaPorcentaje: "80% de palabras leídas correctamente en texto de nivel adecuado",
    intentosSugeridos: "20 palabras por sesión",
    recomendacionClinica: "Comenzar con palabras CVC y CVCV regulares. Evitar palabras con grupos consonánticos hasta lograr dominio básico.",
    indicadorTipo: "Precisión lectora",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-003",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Comprensión lectora",
    franjaEtaria: "6-10",
    franjaEtariaMin: 6,
    franjaEtariaMax: 10,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Comprender textos narrativos breves con preguntas literales e inferenciales",
    definicionOperativa: "El/la paciente responderá correctamente al menos el 75% de preguntas literales e inferenciales sobre textos narrativos de nivel adecuado a su curso escolar.",
    actividadesClinicas: "Lectura de cuentos breves con preguntas guiadas. Actividades de predicción e inferencia. Mapas de historia (personaje, problema, solución). Relectura con foco en detalles.",
    actividadesFamilia: "Leer juntos y hacer preguntas sobre lo leído. Predecir finales de cuentos. Comentar el mensaje del texto.",
    habilidadesRelacionadas: "Decodificación (LE-002), narración (NL-004), inferencia",
    prerequisitos: "Decodificación fluida (LE-002), comprensión oral de textos simples",
    metaPorcentaje: "75% de respuestas correctas en preguntas literales e inferenciales",
    intentosSugeridos: "1 texto por sesión con 5-8 preguntas",
    recomendacionClinica: "Adaptar el nivel de texto al rendimiento lector del paciente. Trabajar vocabulario desconocido antes de la lectura.",
    indicadorTipo: "Preguntas de comprensión",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-004",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Escritura",
    franjaEtaria: "6-10",
    franjaEtariaMin: 6,
    franjaEtariaMax: 10,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Escribir oraciones con ortografía natural y convencional básica",
    definicionOperativa: "El/la paciente producirá oraciones escritas con correcta representación de fonemas (ortografía natural) y uso de mayúsculas, puntuación básica y separación de palabras.",
    actividadesClinicas: "Dictados progresivos. Escritura con apoyo de imagen. Corrección guiada de producciones escritas. Juegos de construcción de oraciones escritas.",
    actividadesFamilia: "Practicar escritura diaria de 3 oraciones sobre su día. Revisar juntos el uso de mayúsculas y punto final. Escribir listas de compras o tareas.",
    habilidadesRelacionadas: "Conciencia fonológica (LE-001), decodificación (LE-002), motricidad fina",
    prerequisitos: "Lectura de palabras regulares (LE-002), praxis grafomotriz básica",
    metaPorcentaje: "80% de palabras escritas correctamente en dictado de 10 palabras conocidas",
    intentosSugeridos: "10 palabras dictadas + 2 oraciones por sesión",
    recomendacionClinica: "Distinguir entre errores ortográficos naturales y convencionales. Priorizar ortografía natural primero.",
    indicadorTipo: "Análisis de escritura",
    estadoBanco: "activo",
  },

  // ─── COGNICIÓN ────────────────────────────────────────────────────────────────
  {
    idObjetivo: "CO-001",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Atención",
    franjaEtaria: "4-10",
    franjaEtariaMin: 4,
    franjaEtariaMax: 10,
    nivelDificultad: "básico",
    nombreObjetivo: "Mantener la atención sostenida en tareas estructuradas por 10-15 minutos",
    definicionOperativa: "El/la paciente completará tareas estructuradas (puzzles, ejercicios de escritura, actividades cognitivas) sin desviaciones conductuales significativas por al menos 10-15 minutos continuos.",
    actividadesClinicas: "Técnicas de regulación atencional. Actividades con incremento gradual de tiempo. Uso de temporizadores visuales. Juegos de concentración y memoria.",
    actividadesFamilia: "Establecer rutinas de estudio con tiempos cortos y descansos. Usar reloj visual. Eliminar distractores durante tareas.",
    habilidadesRelacionadas: "Memoria de trabajo, inhibición de respuesta, regulación emocional",
    prerequisitos: "Atención mínima de 3-5 minutos en tarea de interés",
    metaPorcentaje: "Permanece en tarea 10-15 min en el 80% de las sesiones",
    intentosSugeridos: "Medir en 2 bloques de tarea por sesión",
    recomendacionClinica: "Comenzar con tareas de alta motivación. Usar refuerzo diferencial de atención. Coordinar con equipo escolar si es pertinente.",
    indicadorTipo: "Observación conductual",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-002",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Memoria",
    franjaEtaria: "4-10",
    franjaEtariaMin: 4,
    franjaEtariaMax: 10,
    nivelDificultad: "intermedio",
    nombreObjetivo: "Mejorar la memoria de trabajo verbal (span de dígitos y palabras)",
    definicionOperativa: "El/la paciente incrementará su span de memoria auditiva verbal, recordando y repitiendo secuencias de 4-5 dígitos o palabras no relacionadas en orden correcto.",
    actividadesClinicas: "Tareas de span de dígitos con aumento gradual. Repetición de secuencias de palabras. Estrategias de agrupamiento (chunking). Juegos de memoria auditiva.",
    actividadesFamilia: "Juego de 'repite lo que digo'. Recados verbales de 2-3 elementos. Canciones con listas de elementos.",
    habilidadesRelacionadas: "Atención sostenida (CO-001), procesamiento fonológico, estrategias de codificación",
    prerequisitos: "Atención básica (CO-001), span mínimo de 2-3 elementos",
    metaPorcentaje: "Span de 4 dígitos en 3 de 4 intentos",
    intentosSugeridos: "10 series por sesión",
    recomendacionClinica: "Enseñar estrategias de codificación activa. Evaluar también memoria visual para perfil completo.",
    indicadorTipo: "Span de dígitos y palabras",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-003",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Funciones ejecutivas",
    franjaEtaria: "5-12",
    franjaEtariaMin: 5,
    franjaEtariaMax: 12,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Desarrollar planificación y organización de tareas en pasos secuenciados",
    definicionOperativa: "El/la paciente organizará una tarea compleja (proyecto escolar, receta, plan de juego) en pasos secuenciados lógicamente, identificando el orden correcto y los materiales necesarios.",
    actividadesClinicas: "Planificación de actividades con tarjetas de pasos. Actividades de resolución de problemas en etapas. Role-play de planificación de eventos. Uso de listas de verificación.",
    actividadesFamilia: "Involucrar al niño en planear actividades del hogar. Usar listas de pasos para las rutinas. Revisar juntos el plan antes de ejecutar.",
    habilidadesRelacionadas: "Narrativo (NL-004), atención (CO-001), memoria de trabajo (CO-002), razonamiento",
    prerequisitos: "Secuencias temporales de 3 pasos, atención sostenida básica",
    metaPorcentaje: "Planifica tarea de 5+ pasos correctamente en 3 de 4 oportunidades",
    intentosSugeridos: "1-2 situaciones de planificación por sesión",
    recomendacionClinica: "Comenzar con tareas familiares y de interés del paciente. Usar apoyos visuales en etapas iniciales.",
    indicadorTipo: "Observación de planificación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-004",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Razonamiento",
    franjaEtaria: "4-8",
    franjaEtariaMin: 4,
    franjaEtariaMax: 8,
    nivelDificultad: "básico",
    nombreObjetivo: "Identificar relaciones de causa-efecto en situaciones cotidianas",
    definicionOperativa: "El/la paciente identificará la relación causal entre un evento desencadenante y su consecuencia en situaciones cotidianas presentadas de forma verbal, pictórica o actuada.",
    actividadesClinicas: "Secuencias de causa-efecto con imágenes. Experimentos simples con explicación causal. Role-play de situaciones cotidianas. Preguntas de 'qué pasó porque...'.",
    actividadesFamilia: "Preguntar '¿por qué crees que pasó eso?' en situaciones diarias. Comentar causas de eventos del cuento al leer. Experimentos caseros simples.",
    habilidadesRelacionadas: "Razonamiento inductivo, vocabulario causal (NL-005), comprensión (NL-003)",
    prerequisitos: "Comprensión de 2+ pasos (NL-003), vocabulario básico de acciones",
    metaPorcentaje: "75% de respuestas causa-efecto correctas en 10 situaciones",
    intentosSugeridos: "5-8 situaciones por sesión",
    recomendacionClinica: "Comenzar con relaciones causales físicas antes de sociales o emocionales.",
    indicadorTipo: "Identificación de causa-efecto",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-005",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Flexibilidad cognitiva",
    franjaEtaria: "5-12",
    franjaEtariaMin: 5,
    franjaEtariaMax: 12,
    nivelDificultad: "avanzado",
    nombreObjetivo: "Aplicar estrategias de autorregulación y control inhibitorio",
    definicionOperativa: "El/la paciente aplicará estrategias de autorregulación (pausa antes de responder, respiración, revisión de la tarea) reduciendo respuestas impulsivas en al menos el 70% de los ensayos.",
    actividadesClinicas: "Técnicas de 'para y piensa'. Juegos de inhibición (Stop!). Estrategias de revisión de la propia respuesta. Retroalimentación diferida.",
    actividadesFamilia: "Enseñar la 'tortuga' (parar y pensar). Establecer señales visuales o gestuales para recordar pausar. Reforzar en casa la reflexión antes de actuar.",
    habilidadesRelacionadas: "Atención (CO-001), planificación (CO-003), regulación emocional",
    prerequisitos: "Atención sostenida de 5+ minutos (CO-001), comprensión de normas simples",
    metaPorcentaje: "70% de respuestas con reflexión previa observada en situaciones estructuradas",
    intentosSugeridos: "5 situaciones de control inhibitorio por sesión",
    recomendacionClinica: "Usar refuerzo positivo diferido. Coordinar con equipo escolar para generalización.",
    indicadorTipo: "Observación conductual",
    estadoBanco: "activo",
  },

  // ─── ESTIMULACIÓN TEMPRANA ────────────────────────────────────────────────────
  {
    idObjetivo: "ET-001",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Atención conjunta",
    franjaEtaria: "0-2",
    franjaEtariaMin: 0,
    franjaEtariaMax: 2,
    nivelDificultad: "básico",
    nombreObjetivo: "Establecer y sostener atención conjunta con el cuidador",
    definicionOperativa: "El/la bebé/niño/a dirigirá la mirada hacia el objeto de interés del adulto y alternará la mirada entre el objeto y el adulto al menos 3 veces en 10 minutos de juego libre.",
    actividadesClinicas: "Seguimiento de mirada del clínico hacia juguetes. Actividades de interacción cara a cara. Juegos de atención al objeto de interés. Actividades de señalización.",
    actividadesFamilia: "Hablar con el bebé siguiendo su mirada. Señalar objetos juntos. Leer libros de imágenes señalando y nombrando. Juegos de cara a cara.",
    habilidadesRelacionadas: "Contacto visual (PR-001), gestos comunicativos (PR-004), imitación social",
    prerequisitos: "Ninguno — es el primer hito del desarrollo comunicativo",
    metaPorcentaje: "3+ alternaciones de mirada en 10 minutos de juego libre",
    intentosSugeridos: "Observar en sesión de juego de 15 minutos",
    recomendacionClinica: "Guiar a los padres para seguir los intereses del niño en lugar de redirigir. Evaluar audición y visión si no hay respuesta.",
    indicadorTipo: "Observación de interacción",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-002",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Imitación",
    franjaEtaria: "1-3",
    franjaEtariaMin: 1,
    franjaEtariaMax: 3,
    nivelDificultad: "básico",
    nombreObjetivo: "Imitar acciones y sonidos del adulto en contexto de juego",
    definicionOperativa: "El/la niño/a imitará acciones motoras (aplaudir, agitar objetos, señalar) y vocalizaciones/palabras del adulto en al menos 5 oportunidades durante una sesión de juego.",
    actividadesClinicas: "Juegos de imitación recíproca. Rutinas con turnos imitativos. Modelado de acciones con objetos. Canciones con gestos.",
    actividadesFamilia: "Imitar al niño primero para establecer el turno. Cantar canciones con gestos. Juegos de manos y palmas.",
    habilidadesRelacionadas: "Atención conjunta (ET-001), juego funcional (ET-003), desarrollo motor",
    prerequisitos: "Atención conjunta básica (ET-001)",
    metaPorcentaje: "5+ imitaciones espontáneas en sesión de 20 minutos",
    intentosSugeridos: "Observar en juego interactivo de 20 minutos",
    recomendacionClinica: "Imitar al niño antes de que él imite. Comenzar con imitaciones de objetos antes que gestos corporales.",
    indicadorTipo: "Inventario de imitación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-003",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Juego",
    franjaEtaria: "1-3",
    franjaEtariaMin: 1,
    franjaEtariaMax: 3,
    nivelDificultad: "básico",
    nombreObjetivo: "Desarrollar juego funcional y simbólico básico",
    definicionOperativa: "El/la niño/a usará objetos según su función (peinar muñeca, alimentar oso) y desarrollará secuencias de juego simbólico de al menos 2 acciones encadenadas.",
    actividadesClinicas: "Modelado de uso funcional de objetos. Juego simbólico con roles simples. Uso de miniaturas temáticas. Rutinas de juego con muñecos.",
    actividadesFamilia: "Jugar con el niño usando objetos cotidianos de forma funcional. Modelar juego de 'hacer como si...'. Proporcionar juguetes que inviten al juego simbólico.",
    habilidadesRelacionadas: "Imitación (ET-002), vocabulario (NL-001), atención conjunta (ET-001)",
    prerequisitos: "Imitación de acciones con objetos (ET-002)",
    metaPorcentaje: "Secuencia de juego simbólico de 2+ acciones en 3 sesiones consecutivas",
    intentosSugeridos: "Observar en juego libre de 20 minutos",
    recomendacionClinica: "Seguir el liderazgo del niño en el juego. No estructurar demasiado; permitir la espontaneidad.",
    indicadorTipo: "Escala de juego",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-004",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Comunicación preverbal",
    franjaEtaria: "0-2",
    franjaEtariaMin: 0,
    franjaEtariaMax: 2,
    nivelDificultad: "básico",
    nombreObjetivo: "Aumentar las vocalizaciones y balbuceos canónicos intencionales",
    definicionOperativa: "El/la bebé producirá balbuceos canónicos (CV: ba, ma, da) y vocalizaciones variadas con intencionalidad comunicativa (para llamar la atención, pedir, comentar).",
    actividadesClinicas: "Estimulación vocal en rutinas. Respuesta contingente a vocalizaciones. Juegos vocales cara a cara. Canciones y rimas con vocalizaciones.",
    actividadesFamilia: "Responder contingentemente a cada vocalización del bebé. Imitar sus sonidos de vuelta. Cantar y hablar al bebé durante rutinas de cuidado.",
    habilidadesRelacionadas: "Atención conjunta (ET-001), imitación (ET-002), precursores del lenguaje",
    prerequisitos: "Ninguno — objetivo para etapa pre-léxica",
    metaPorcentaje: "8+ vocalizaciones intencionales en 15 minutos de interacción",
    intentosSugeridos: "Observar y registrar en sesión de 15 minutos",
    recomendacionClinica: "Orientar a los padres sobre la importancia de responder a cada vocalización del bebé. Evaluar audición si no hay respuesta.",
    indicadorTipo: "Frecuencia de vocalizaciones",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-005",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Primeras palabras",
    franjaEtaria: "1-3",
    franjaEtariaMin: 1,
    franjaEtariaMax: 3,
    nivelDificultad: "básico",
    nombreObjetivo: "Ampliar el léxico hasta las primeras 50 palabras funcionales",
    definicionOperativa: "El/la niño/a producirá un repertorio de al menos 50 palabras (sustantivos, verbos, palabras sociales) usadas espontáneamente en contextos variados.",
    actividadesClinicas: "Intervención sobre vocabulario en contexto. Modelado de palabras en rutinas. Estimulación focalizada de palabras objetivo. Lectura de cuentos con denominación.",
    actividadesFamilia: "Nombrar todo el entorno durante las rutinas. Leer libros de imágenes a diario. Responder a intentos comunicativos del niño expandiendo su lenguaje.",
    habilidadesRelacionadas: "Balbuceo (ET-004), imitación (ET-002), atención conjunta (ET-001)",
    prerequisitos: "Primeras palabras emergentes (al menos 5-10 palabras), imitación presente",
    metaPorcentaje: "50 palabras espontáneas en inventario de vocabulario",
    intentosSugeridos: "Inventario mensual + estimulación de 5-8 palabras nuevas por semana",
    recomendacionClinica: "Usar MacArthur CDI o similar para seguimiento. Trabajar palabras de alta frecuencia en el entorno del niño.",
    indicadorTipo: "Inventario de vocabulario",
    estadoBanco: "activo",
  },
];

async function main() {
  console.log("Seeding goal library with extended fields...");
  for (const goal of goals) {
    await db.insert(goalLibraryTable).values(goal as any).onConflictDoUpdate({
      target: goalLibraryTable.idObjetivo,
      set: {
        franjaEtariaMin: (goal as any).franjaEtariaMin,
        franjaEtariaMax: (goal as any).franjaEtariaMax,
        habilidadesRelacionadas: (goal as any).habilidadesRelacionadas,
        prerequisitos: (goal as any).prerequisitos,
        subarea: (goal as any).subarea,
        actividadesClinicas: (goal as any).actividadesClinicas,
        actividadesFamilia: (goal as any).actividadesFamilia,
        recomendacionClinica: (goal as any).recomendacionClinica,
      },
    });
  }
  console.log(`Done — ${goals.length} goals seeded/updated.`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
